kind: pipeline
type: docker
name: slack-test

steps:
  - name: test
    image: alpine
    commands:
      - echo "Testing Drone Slack notification"

  - name: slack-notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: "#general"
      username: "Drone CI"
      icon_emoji: ":rocket:"
      message: |
        🚀 *Drone CI Notification*
        *Repo:* {{ repo.name }}
        *Branch:* {{ build.branch }}
        *Build:* #{{ build.number }}
        *Status:* {{ build.status }}
        *Commit:* {{ truncate commit.sha 7 }}
        *Author:* {{ commit.author }}
    when:
      status:
        - success
        - failure
